
TYPE
	CtrlType : 	STRUCT  (*Control type*)
		AlarmInsID : UDINT; (*Alarm instance ID*)
		AlarmSensorName : STRING[10]; (*Alarm sensor name*)
		SetupCategory : STRING[50]; (*Setup category*)
		RecipeCategory : STRING[50]; (*Recipe category*)
		StatusIDConfig : DGDataSaveLogStatusIDConfigType; (*StatusID config*)
		DiagCounters : CtrlDiagCountersType; (*Diagnostic counters*)
		Internal : CtrlInternalType; (*Internal*)
	END_STRUCT;
	CtrlDiagCountersType : 	STRUCT  (*Control internal diagnostic counters type*)
		ErrorCnt : UDINT; (*Error counter*)
		TurnTableCnt : UDINT; (*Command counter*)
		ErrorResetCnt : UDINT; (*Error reset counter*)
	END_STRUCT;
	CtrlInternalType : 	STRUCT  (*Control internal type*)
		Edges : CtrlInternalEdgesType; (*Edges structure*)
		Timers : CtrlInternalTimersType; (*Timers*)
		StatusIDOld : DINT; (*StatusID old*)
		MpRecipeRegPar_0 : MpRecipeRegPar; (*MpRecipeRegPar mapp component*)
		MpRecipeRegPar_1 : MpRecipeRegPar; (*MpRecipeRegPar mapp component*)
		MachineModeOld : USINT; (*Machine mode old*)
		MpAxisBasic_0 : MpAxisBasic; (*MpAxisBasic mapp component*)
		MpAxisBasicConfig_0 : MpAxisBasicConfig; (*MpAxisBasicConfig mapp component*)
		MpAxisParameters : MpAxisBasicParType; (*MpAxisBasic parameters*)
		MpAxisConfig : MpAxisBasicConfigType; (*MpAxisBasic configuration*)
		MpAxisPowerOnChange : BOOL; (*MpAxisBasic power on change*)
		MCExtHwEndSw_0 : MCExtHwEndSw; (*MCExtHwEndSw FB*)
		MCExtHwEndSwConfig : MCExtHwEndSwConfigType; (*Configuration hardware end switch*)
		ActiveCmd : CtrlInternalActCmdType; (*Active command structure*)
		OutPositionOld : BOOL; (*Turn table out position old*)
		DirectHomeMode : BOOL; (*Direct home mode*)
		SlowBeforeInPos : BOOL; (*Slow down before in position*)
		SlowBeforeInPosOld : BOOL; (*Slow down before in position*)
	END_STRUCT;
	CtrlInternalEdgesType : 	STRUCT  (*Control internal edges type*)
		Pos_0 : BOOL; (*Edge positive*)
		Pos_1 : BOOL; (*Edge positive*)
		Pos_2 : BOOL; (*Edge positive*)
		Pos_3 : BOOL; (*Edge positive*)
		Pos_4 : BOOL; (*Edge positive*)
		Pos_5 : BOOL; (*Edge positive*)
		Pos_6 : BOOL; (*Edge positive*)
		Pos_7 : BOOL; (*Edge positive*)
		Pos_8 : BOOL; (*Edge positive*)
		Pos_9 : BOOL; (*Edge positive*)
		Neg_0 : BOOL; (*Edge negative*)
	END_STRUCT;
	CtrlInternalTimersType : 	STRUCT  (*Control internal timers type*)
		TON_0 : TON; (*TON FB*)
		TON_1 : TON; (*TON FB*)
		TON_2 : TON; (*TON FB*)
	END_STRUCT;
	CtrlInternalActCmdType : 	STRUCT  (*Control active command type*)
		Power : BOOL; (*Power*)
		Home : BOOL; (*Home*)
		TurnTable : BOOL; (*Active command*)
	END_STRUCT;
END_TYPE
