
TYPE
	TBLCtrlInterfaceType : 	STRUCT  (*Interface control interface type*)
		Cmd : TBLCtrlIntfCmdType; (*Commads*)
		Mon : TBLCtrlIntfMonType; (*Monitor*)
	END_STRUCT;
	TBLCtrlIntfCmdType : 	STRUCT  (*Interface control commands type*)
		Init : BOOL; (*Init*)
		Power : BOOL; (*Power*)
		Home : BOOL; (*Home*)
		TurnTable : BOOL; (*Turn table*)
		JogPosTable : BOOL; (*Jog pos table*)
		JogNegTable : BOOL; (*Jog neg table*)
		Stop : BOOL; (*Stop*)
		SaveConfig : BOOL; (*Save configuration*)
		LoadConfig : BOOL; (*Load configuration*)
		ErrorReset : BOOL; (*Error reset*)
	END_STRUCT;
	TBLCtrlIntfMonType : 	STRUCT  (*Interface control monitor type*)
		Error : BOOL; (*Error active*)
		StatusID : DINT; (*StatusID*)
		Busy : BOOL; (*Busy*)
		InitDone : BOOL; (*Init done*)
		TurnTableDone : BOOL; (*Turn table done*)
		PowerDone : BOOL; (*Power done*)
		HomeDone : BOOL; (*Home done*)
		StopDone : BOOL; (*Stop done*)
		BlockJogTable : BOOL; (*Block jog table*)
		State : TBLCtrlIntfMonStateEnum; (*State*)
		Info : TBLCtrlIntfMonInfoType; (*Info structure*)
	END_STRUCT;
	TBLCtrlIntfMonStateEnum : 
		( (*Interface control monitor state enumeration*)
		tblCTRL_ST_WAIT_CMD := 0, (*Waiting for commands*)
		tblCTRL_ST_ACTIVE_ALM_SYS_W := 5, (*Wait for active alarm system*)
		tblCTRL_ST_INIT_HW_END_SW := 6, (*Init hardware end switch*)
		tblCTRL_ST_POWER_ON_AXIS := 10, (*Power on axis*)
		tblCTRL_ST_POWER_OFF_AXIS := 11, (*Power off axis*)
		tblCTRL_ST_HOME_AXIS := 20, (*Home axis*)
		tblCTRL_ST_READY_TURN_TABLE := 30, (*Control ready to turn table*)
		tblCTRL_ST_TURN_TABLE := 31, (*Turn table*)
		tblCTRL_ST_JOG_POS := 40, (*Jog positive*)
		tblCTRL_ST_JOG_NEG := 41, (*Jog negative*)
		tblCTRL_ST_STOP := 500 (*Stop*)
		);
	TBLCtrlIntfMonInfoType : 	STRUCT  (*Interface control monitor info type*)
		Status : TBLCtrlIntfMonInfoStatusEnum; (*Status*)
		ErrorBlink : BOOL; (*Error blink*)
		PowerOn : BOOL; (*Turn table is power on*)
		IsHomed : BOOL; (*Turn table is homed*)
		MoveActive : BOOL; (*Turn table move active*)
		InPosition : BOOL; (*Turn table is in position*)
		OutPosition : BOOL; (*Turn table is out position*)
		Position : LREAL; (*Position of turn table*)
		Velocity : REAL; (*Velocity of turn table*)
		StationInPos : BOOL; (*Station are in position*)
		Diag : TBLCtrlIntfMonDiagType; (*Diagnostic structure*)
	END_STRUCT;
	TBLCtrlIntfMonDiagType : 	STRUCT  (*Interface control monitor diagnostic type*)
		LastErrorStates : ARRAY[0..tblCTRL_LAST_ERR_STATE_NUM_INDX]OF TBLCtrlIntfMonStateEnum; (*Last error states*)
		LastStates : ARRAY[0..tblCTRL_LAST_STATE_NUM_INDX]OF TBLCtrlIntfMonStateEnum; (*Last states*)
		Parts : TBLCtrlIntfMonDiagPartsType; (*Diagnostic parts structure*)
	END_STRUCT;
	TBLCtrlIntfMonDiagPartsType : 	STRUCT  (*Interface control monitor diagnostic parts type*)
		StatusID : TBLCtrlIntfMonDiagStatusIDType; (*StatusID structure*)
		Internal : CSComMonDiagInternalLevel1Type; (*Internal structure*)
	END_STRUCT;
	TBLCtrlIntfMonDiagStatusIDType : 	STRUCT  (*Interface control monitor diagnostic StatusID type*)
		ID : TBLCtrIntfErrorEnum; (*StatusID*)
		Severity : CSComSeveritiesEnum; (*Severity of the StatusID*)
		Code : UINT; (*Code of the StatusID*)
	END_STRUCT;
	TBLCtrlIntfFacilityEnum : 
		( (*Interface control facility enumeration*)
		tblCTRL_FAC := 15 (*Interface control facility*)
		);
	TBLCtrlIntfMonInfoStatusEnum : 
		( (*Interface control monitor info status enumeration*)
		tblCTRL_STATUS_IDLE := 0, (*IDLE*)
		tblCTRL_STATUS_ACTIVE := 10, (*ACTIVE*)
		tblCTRL_STATUS_AUTOMAT_MODE := 50, (*AUTOMAT MODE IS ACTIVE*)
		tblCTRL_STATUS_POWER := 100, (*POWER*)
		tblCTRL_STATUS_HOME := 101, (*HOMING*)
		tblCTRL_STATUS_JOG_POS := 110, (*JOG POS*)
		tblCTRL_STATUS_JOG_NEG := 111, (*JOG NEG*)
		tblCTRL_STATUS_ST_NOT_IN_POS := 120, (*STATIONS ARE NOT IN POSITION*)
		tblCTRL_STATUS_ERROR := 1000 (*ERROR*)
		);
END_TYPE
